[tool.poetry]
name = "healpix-alchemy"
version = "0.1.0"
description = "SQLAlchemy extensions for HEALPix spatially indexed astronomy data"
authors = ["Leo Singer <leo.singer@ligo.org>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "*"
astropy = "*"

[tool.poetry.dev-dependencies]
psycopg2-binary = "*"
pytest = "*"
pytest-postgresql = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
