name: Post comment

on:
  workflow_run:
      workflows: [ "Build and test" ]
      types:
        - completed

jobs:

  post_comment:
      runs-on: ubuntu-latest
      steps:
      - name: Comment on triggering event
        uses: actions/github-script@v5
        with:
          script: |
            const artifacts = await github.request('GET /repos/bparazin/healpix-alchemy/actions/artifacts')
            console.log(typeof artifacts)
            const url = github.request('GET /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: 'runtime-plots',
              archive_format: 'zip'
            })
            console.log(url)
            if (context.eventName === 'pull_request'){
              console.log(context.payload['after'])
              github.rest.repos.createCommitComment({
                commit_sha: context.payload['after'],
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: url
              })
            }